
server:
  port: 8080
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: ${hello-cafe.datasource.driver-class-name}
    url: jdbc:mysql://${hello-cafe.datasource.host}:${hello-cafe.datasource.port}/${hello-cafe.datasource.database}?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    username: ${hello-cafe.datasource.username}
    password: ${hello-cafe.datasource.password}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  data:
    redis:
      host: ${hello-cafe.redis.host}
      port: ${hello-cafe.redis.port}
      database: ${hello-cafe.redis.database}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  security:
    user:
      name: admin
      password: admin123
hello-cafe:
  jwt:
    admin-secret-key: ${hello-cafe.jwt.adminSecretKey}
    admin-ttl: ${hello-cafe.jwt.adminTtl}
    admin-token-name: ${hello-cafe.jwt.adminTokenName}

    user-secret-key: ${hello-cafe.jwt.userSecretKey}
    user-ttl: ${hello-cafe.jwt.userTtl}
    user-token-name: ${hello-cafe.jwt.userTokenName}
  aws:
    s3:
      bucket-name: ${hello-cafe.aws.s3.bucket-name}
      region: ${hello-cafe.aws.s3.region}
      access-key: ${hello-cafe.aws.s3.accessKey}
      secret-key: ${hello-cafe.aws.s3.secretKey}

logging:
  level:
    com:
      hello-cafe:
        repository: DEBUG
        service: DEBUG
        controller: DEBUG


